### ISSUE TITLE
VCチャンネルに自動参加させる機能を実装させたい

### ISSUE THREAD

**Issue by AzukiShiratama** [notoiro/kana#1]
初めまして。
こちらのBOTをローカルのWindows上で使わせていただきたいと思っております。
ですが、個人的に必須である、VCチャンネルに誰かが参加した時にBOTを自動参加させるという機能の実装に難航しております。
当方プログラミングの知識に乏しいため、もしよろしければ具体的なコード案をご教示頂けませんでしょうか？
お忙しいところ申し訳ありませんが、よろしくお願いいたします。

**Comment by notoiro** [comment]
はじめまして。

私はその機能については、設計思想上作るつもりはなく、PRされたとしてマージすることはないですが、実装としては割と簡単な部類ではあると思うので、実装の際に参考になる部分へのリンク付きで実装案だけ置いておきます。

**実装案1: JOIN先の指定をするコマンドを作る。指定されたJOIN先を監視して、そこにユーザーが参加したら参加する。** 
- メリット: 
    - 接続先1つ限定になるのでブラックリストとか作らなくていい。
    - Botが勝手に入ってこないチャンネルも作れる。
    - 利便性とプライバシーの間の妥協ライン。
- デメリット: 
    - 実装がそこそこ面倒。
    - 内部の設定ファイルがJSONファイルなので頻繁にディスクにアクセスすることになる。
    - サーバー管理者側で接続先設定必要だし、接続先設定ない時の処理も必要。
- 注意点: 
    - このBotの実装上、設定ファイルの項目が増えることを想定していないで書かれているので、設定の読み込み書き込みの実装は各所に点在している。
    - 接続済かのチェックを忘れないこと。
    - ユーザーが参加したVCが接続先かのチェックも忘れないこと。
    - コマンドはサーバー管理者であるかのチェックを忘れないこと。

- 実装
  1. コマンド定義して
    https://github.com/notoiro/discord-multitool/blob/master/index.js#L80-L92
  2. コマンド中身作る
    https://github.com/notoiro/discord-multitool/blob/master/index.js#L235-L253
  3. このBotには元々辞書とか声用に設定のJSONファイルあるのでそこに書き込んじゃう 
    https://github.com/notoiro/voicevox-tts-discord/blob/master/src/index.js#L802-L806
    https://github.com/notoiro/voicevox-tts-discord/blob/master/src/index.js#L825
  4. JOIN監視の実装はこの辺り改造して書く(多分スコープ分けて2つ並べちゃうと楽)
    https://github.com/notoiro/voicevox-tts-discord/blob/master/src/index.js#L658-L700
  5. 元の通話接続処理を接続の処理とインタラクション前提の処理に分けてJOIN監視から接続の処理だけ呼び出せるようにする。それをJOIN処理から呼び出せるようにすれば完成。
    https://github.com/notoiro/voicevox-tts-discord/blob/master/src/index.js#L554-L656


**実装案2: サーバー内のVC全部を監視対象として、とにかくユーザーが参加したら参加する。**
- メリット: 
  - 比較的簡単に作れる。
  - 設定ファイルとかいらないのでディスクにやさしい。
  - 手動の設定いらないので楽。
- デメリット: 
  - 接続してほしくないチャンネルとかあるとブラックリストなりなんなり作る必要がある。
  - 複数サーバーで使うとON/OFFの実装もほしくなる。
- 注意点: 接続済かのチェックを忘れないこと。

- 実装
  1. JOIN監視の実装はこの辺り改造して書く(多分スコープ分けて2つ並べちゃうと楽)
    https://github.com/notoiro/voicevox-tts-discord/blob/master/src/index.js#L658-L700
  2. 元の通話接続処理を接続の処理とインタラクション前提の処理に分けてJOIN監視から接続の処理だけ呼び出せるようにする。それをJOIN処理から呼び出せるようにすれば完成。
    https://github.com/notoiro/voicevox-tts-discord/blob/master/src/index.js#L554-L656


では。

**Comment by AzukiShiratama** [comment]
アドバイス頂きありがとうございます！
プログラミングを齧る程度しか経験したことがないので、自分なりに頭を捻って以下のような感じまで進めてみました。

**setautojoin.js**
```module.exports = {
  data: {
    name: "setautojoin",
    description: "自動参加の設定",
    options: [
      {
        type: ApplicationCommandOptionType.Channel,
        name: "autojoin",
        channel_types: [ChannelType.GuildVoice],
        description: "自動参加",
        required: true
      }
    ]
  }
}
```
**index.js**
```  async setautojoin(interaction){
    const guild = interaction.guild;
    if(!(interaction.member.permissions.has('Administrator'))){
      interaction.reply("管理者になって出直して");
      return;
    }

    const data = {
      autojoin: interaction.options.get("autojoin").value
    }
    try{
      fs.writeFileSync(`${SERVER_DIR}/${guild.id}.json`, JSON.stringify(data));
    }catch(e){
      console.log(e);
      return;
    }

    interaction.reply("セットしたよ");
    
    const server_file = this.get_server_file(guild_id);
    if(server_file){
      autojoin = server_file.user_voices ?? autojoin;
    }

    this.write_serverinfo(guild_id, { user_voices: autojoin });

  }
```

根本的に間違っているかもしれないのですが、宜しければ引き続きアドバイス頂けますと幸いです。
次はJOIN監視の実装部分ですが、ここがかなり難しそうな感じです。
