### ISSUE TITLE
グローバル辞書機能の実装

### ISSUE THREAD

**Issue by YTJVDCM** [notoiro/kana#2]
# 概要

現時点で主に英単語周りの読みが壊滅的なので、Kagomeによる形態素解析による読み補正に加え、別途全サーバーにおいて作用するグローバル辞書機能の実装を提案します。

# 実装案

現時点でグローバル辞書自体は辞書ファイルをサーバー側に登録し、それに準じた変換をテキスト処理の段階で行う

原則としてユーザー辞書を優先し、Kagome側で処理可能な固有名詞はそちらを優先したいため、fix_reading時にグローバル辞書の適用を行うのが無難？

# グローバル辞書ファイルの実装

グローバル辞書の定義ファイル格納用ディレクトリを新規に作成し、その中に辞書変換定義ファイルを配置する方式が無難そう。
ファイル形式やフォーマットについては議論の余地あり。

# 備考

全サーバーに影響する内容であるため、現時点でユーザーサイドからの登録機能については考えないものとする。
(これについては実装する場合、別途issue立てを行ったほうが良さそう)

**Comment by YTJVDCM** [comment]
グローバル辞書ファイルもユーザー定義辞書と同様に`[単語,読み,優先度]`で区切られたJSONとして実装する形が全体のファイルフォーマットの統一もできるので無難そう？

**Comment by notoiro** [comment]
実質作ったようなもんなので
